### ISSUE TITLE
[🚀]: Настройка формата сообщения

### ISSUE THREAD

**Issue by jtprogru** [jtprogru/gtga#2]
### What are you functionality want?

Необходимо добавить функцию считывая конфигурации из файла, для того чтобы задавать формат и шаблон сообщений.

Например:

```yaml
---
tpl:
  before_msg: `<b>Важное сообщение!</b>`
  after_msg: `Тегать @username`
```

А между `before_msg` и `after_msg` будет уже то, что передано через флаг `-msg`.
